[package]
name = "birc-rapidnj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
petgraph = "0.6.4"
rand = "0.8.5"
seq_io = "0.3.2"
trees = "0.4.2"
